# general config
model_class: 'cement'

verbose: False

# data sources
input_data_path: '../simson_data/data/cement/output'

# model customization
customization:
  curve_strategy: 'Exponential_GDP_regression'
  ldf_type: 'LogNormal'
  product_dimension_name: 'Good'

# visualization
visualization:
  use_stock:
    do_visualize: False
    over_time: True
    over_gdp: False
    per_capita: True
  eol_stock:
    do_visualize: True
    over_time: True
    over_gdp: False
    per_capita: False
  clinker_production:
    do_visualize: True
  cement_production:
    do_visualize: True
  concrete_production:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
    split_flows_by: 'Stock Type'
    color_scheme: 'blueish'
    flow_color: 'hsl(230,20,70)'
    exclude_processes:
      - "sysenv"
    exclude_flows: [ ]
  do_show_figs: True
  do_save_figs: False
  plotting_engine: 'plotly'

# data export
output_path: 'data/cement/output'
do_export:
  pickle: True
  csv: True
