# general config
model_class: 'plastics'

# data sources
input_data_path: 'data/plastics/input'

# model customization
customization:
  stock_extrapolation_class_name: 'PehlExtrapolation'
  lifetime_model_name: 'NormalLifetime'

# visualization
visualization:
  stock:
    do_visualize: True
    # options: 'time', 'gdppc'
    over: 'gdppc'
    per_capita: True
  production:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2015
      r: "CHA"
    split_flows_by: 'Material'
    color_scheme: 'blueish'
    flow_color: 'hsl(230,20,70)'
    exclude_processes:
      - "sysenv"
    exclude_flows: [ ]
  do_show_figs: True
  do_save_figs: False

# data export
output_path: 'data/plastics/output'
do_export:
  pickle: False
  csv: True
