
# general config
model_class: 'plastics'

do_show_figs: True
do_save_figs: True

verbose: False

# data sources
data_path: 'data/plastics'

# model customization
curve_strategy: 'GDP_regression'
ldf_type: 'Normal'

do_visualize:
  'stock_prediction': False
  'future_production': False
  'sankey': True
