# general config
model_class: 'steel'

# data sources
input_data_path: '../simson_data/data/steel/output'

# model customization
customization:
  stock_extrapolation_class_name: 'FixedSatLogSigmoidExtrapolation'
  lifetime_model_name: 'LogNormalLifetime'
  do_stock_extrapolation_by_category: True

# visualization
visualization:
  scrap_demand_supply:
    do_visualize: False
  sector_splits:
    do_visualize: False
  stock:
    do_visualize: True
    over_gdp: True
    per_capita: True
  production:
    do_visualize: True
  sankey:
    do_visualize: False
    slice_dict:
      t: 2020
      # r: 'USA'
    exclude_processes:
      - "sysenv"
      - "imports"
      - "exports"
    exclude_flows: [ ]
  do_show_figs: True
  do_save_figs: False
  plotting_engine: 'plotly'

# data export
output_path: 'data/steel/output'
do_export:
  pickle: False
  csv: False
