# general config
model_class: 'steel'

verbose: False

# data sources
input_data_path: '../simson_data/data/steel/output'

# model customization
customization:
  curve_strategy: 'Exponential_GDP_regression'
  ldf_type: 'LogNormal'
  product_dimension_name: 'Good'

# visualization
visualization:
  scrap_demand_supply:
    do_visualize: True
  sector_splits:
    do_visualize: True
  stock:
    do_visualize: True
    over_gdp: False
    per_capita: True
  production:
    do_visualize: True
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
    split_flows_by: 'Good'
    color_scheme: 'blueish'
    flow_color: 'hsl(230,20,70)'
    exclude_processes:
      - "sysenv"
    exclude_flows: [ ]
  do_show_figs: True
  do_save_figs: True
  plotting_engine: 'plotly'

# data export
output_path: 'data/steel/output'
do_export:
  pickle: True
  csv: True
