# general config
model_class: 'steel'

verbose: False

# data sources
input_data_path: '../steel_data/input'
# input_data_path: 'data/steel/input/'

# model customization
model_customization:
  curve_strategy: 'Exponential_GDP_regression'
  ldf_type: 'Normal'
  product_dimension_name: 'Good'
  has_scenarios: True

# visualization
visualization:
  stock:
    do_visualize: False
    # options: 'time', 'gdppc'
    over: 'gdppc'
    per_capita: False
  production:
    do_visualize: False
  sankey:
    do_visualize: True
    slice_dict:
      t: 2050
    split_flows_by: 'Material'
    color_scheme: 'blueish'
    flow_color: 'hsl(230,20,70)'
    exclude_processes:
    - "sysenv"
    exclude_flows: []
  do_show_figs: True
  do_save_figs: True

# data export
output_path: 'data/steel/output'
do_export:
  pickle: True
  csv: True
