# general config
model_class: 'steel'

verbose: False

# data sources
input_data_path: 'data/steel/input'
output_path: 'data/steel/output'

# model customization
curve_strategy: 'GDP_regression'
ldf_type: 'Normal'
product_dimension_name: 'Good'
has_scenarios: True

visualize:
  stock:
    do_visualize: False
    # options: 'time', 'gdppc'
    over: 'gdppc'
    per_capita: False
  production:
    do_visualize: False
  sankey:
    do_visualize: True
do_show_figs: True
do_save_figs: True

do_export:
  pickle: True
  csv: True
